theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: ["Parkhi Rastogi"]
description: ["Engineering Portfolio â€” C++ Systems, Backend Development & API Design"]
